### ISSUE TITLE
Quels sont les "achats"?

### ISSUE THREAD

**Issue by eliannelavoie** [QR-Quebec/issues#1]
On mentionne des "achats" sur le site web et dans la FAQ, mais je n'ai pas trouvé d'explication de c'est quoi qu'on peut acheter.

C'est quoi les achats? Va-il y avoir des fonctionnalités payantes?

**Comment by AphgaDesign** [comment]
QR-Québec est gratuit pour 3 passeports. Pour  entreposer plus de passeports, nous demandons 99¢, jusqu'à 10 passeports.
